### ISSUE TITLE
Check, but no end of game.

### ISSUE THREAD

**Issue by who0ps** [cxjdavin/tgchessbot#1]
White to move.
There is no end.
![default](https://cloud.githubusercontent.com/assets/17404606/22569659/13f83a14-e9a1-11e6-9363-55e19bef8e8f.png)

**Comment by cxjdavin** [comment]
Thanks for your feedback! :)
Sorry I haven't been free to get back to you promptly.

This should fix it:
https://github.com/cxjdavin/tgchessbot/commit/0c41f9f8253acb6421a7511cf601e7d7effac3a5

**Comment by who0ps** [comment]
Not fixed.
![photo6134386271892645890](https://cloud.githubusercontent.com/assets/17404606/22991811/3343843a-f3c6-11e6-8130-8483371b99f7.jpg)
(White to move)

**Comment by schubtob** [comment]
I ran into the same issue today, and I have found the problem. I will create a pull request that explains and fixes it.
